declare const classes: {
  readonly controls: string;
  readonly controlsFrameless: string;
  readonly controlsMacOs: string;
  readonly controlsMacOsTrafficLights: string;
  readonly macOsPinControl: string;
  readonly macOsRestartAfterTrafficLights: string;
  readonly trafficLight: string;
  readonly trafficLightClose: string;
  readonly trafficLightGlyph: string;
  readonly trafficLightMaximize: string;
  readonly trafficLightMinimize: string;
  readonly trafficLightRestart: string;
  readonly trafficLightRestartGlyph: string;
  readonly windowControlButton: string;
  readonly windowControlButtonClose: string;
  readonly windowControlButtonPinActive: string;
  readonly windowControlButtonRestart: string;
};
export default classes;
