declare const classes: {
  readonly navButton: string;
  readonly navButtonActive: string;
  readonly navChildButton: string;
  readonly navChildItem: string;
  readonly navChildList: string;
  readonly navGroup: string;
  readonly navGroupChevron: string;
  readonly navGroupChevronOpen: string;
  readonly navIcon: string;
  readonly navItem: string;
  readonly navLabel: string;
  readonly navList: string;
  readonly navTooltipHost: string;
  readonly panel: string;
  readonly panelExpanded: string;
  readonly panelInner: string;
  readonly panelInnerExpanded: string;
  readonly rail: string;
  readonly toggleButton: string;
  readonly toggleSlot: string;
};
export default classes;
