/* Generated by scripts/generate-css-modules-dts.mjs — do not edit. */
declare const styles: {
  readonly cancelChevron: string;
  readonly cancelGroup: string;
  readonly content: string;
  readonly description: string;
  readonly footer: string;
  readonly header: string;
  readonly menu: string;
  readonly modeList: string;
  readonly title: string;
};
export = styles;
