declare const classes: {
  readonly callActionDivider: string;
  readonly callActionGroup: string;
  readonly callActionGroupActionable: string;
  readonly callActionLabel: string;
  readonly callActionReason: string;
  readonly callActionSegment: string;
  readonly callActionSegmentBusy: string;
  readonly callActionSegmentCall: string;
  readonly callActionSegmentHost: string;
  readonly callActionSegmentReady: string;
  readonly callActionSegmentVideo: string;
  readonly deleteButton: string;
  readonly inputActionButton: string;
  readonly inputField: string;
  readonly inputRow: string;
  readonly key: string;
  readonly keyDigit: string;
  readonly keyDisabled: string;
  readonly keySub: string;
  readonly keys: string;
  readonly overlayHeader: string;
  readonly overlayTitle: string;
  readonly panel: string;
  readonly panelInputDisabled: string;
  readonly panelOverlay: string;
};
export default classes;
