declare const classes: {
  readonly actionButton: string;
  readonly actionButtons: string;
  readonly answerButton: string;
  readonly answerVideoButton: string;
  readonly autoAnswerFill: string;
  readonly autoAnswerHint: string;
  readonly autoAnswerTrack: string;
  readonly card: string;
  readonly cardSelected: string;
  readonly disabledReason: string;
  readonly iconCircle: string;
  readonly identity: string;
  readonly incomingHint: string;
  readonly mainRow: string;
  readonly mainRowForeground: string;
  readonly primaryName: string;
  readonly rejectButton: string;
  readonly rowSurface: string;
  readonly secondaryNumber: string;
  readonly statusBlock: string;
};
export default classes;
