declare const classes: {
  readonly actionButton: string;
  readonly actionButtons: string;
  readonly anchor: string;
  readonly answerButton: string;
  readonly autoAnswerFill: string;
  readonly autoAnswerHint: string;
  readonly autoAnswerTrack: string;
  readonly body: string;
  readonly dismissButton: string;
  readonly iconCircle: string;
  readonly identity: string;
  readonly mainRow: string;
  readonly mainRowForeground: string;
  readonly overlay: string;
  readonly primaryName: string;
  readonly rejectButton: string;
  readonly rowSurface: string;
  readonly secondaryNumber: string;
  readonly statusBlock: string;
};
export default classes;
