declare const classes: {
  readonly card: string;
  readonly cardLabel: string;
  readonly cardLabelText: string;
  readonly cardSelected: string;
  readonly content: string;
  readonly error: string;
  readonly footer: string;
  readonly grid: string;
  readonly header: string;
  readonly layout: string;
  readonly status: string;
  readonly tab: string;
  readonly tabActive: string;
  readonly tabs: string;
  readonly thumb: string;
  readonly thumbIcon: string;
  readonly thumbPlaceholder: string;
};
export default classes;
